In [1]:
#1. Import NumPy and print its version.
import numpy as np
import pandas as pd
print("Numpy version:",np.__version__)

Numpy version: 2.5.3


In [2]:
df = pd.read_csv("it_services_tickets_raw.csv")

In [3]:
#2. Make an array from the hours logged column.
df["hours_logged"] = pd.to_numeric(df["hours_logged"],errors="coerce")
hours = df["hours_logged"].to_numpy().copy()
print(hours)

[ nan 1.34 7.   ... 5.   2.    nan]


In [4]:
#3. Print the shape, the size and the data type of that array.
print("Shape:", hours.shape)
print("Size:", hours.size)
print("Data type:", hours.dtype)

Shape: (49588,)
Size: 49588
Data type: float64


In [5]:
#4. Make an array of the numbers 1 to 50 using arange.
arr = np.arange(1, 51)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [6]:
#5. Make 10 evenly spaced numbers between 0 and 100 using linspace.
arr = np.linspace(0, 100, 10)
print(arr)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [7]:
#6. Make an array of 10 zeros and an array of 10 ones.
zeros = np.zeros(10)
ones = np.ones(10)
print(zeros)
print(ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
#7. Make a 3 by 3 array of random numbers using seed 42.
np.random.seed(42)
random_array = np.random.rand(3, 3)
print(random_array)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [9]:
#8. Make a 2-D array from the hours logged and billing rate columns.
ticket_data = np.column_stack((df["hours_logged"],df["Billing Rate (USD)"]))
print(ticket_data)


[[nan '$39.45']
 [1.34 '33.15']
 [7.0 '48.10']
 ...
 [5.0 '24.94']
 [2.0 '$116.76']
 [nan ' 89.02 ']]


In [10]:
#9. Print how many dimensions that 2-D array has.
print(ticket_data.ndim)

2


In [11]:
#10. Print the first 5 values of the hours array.
hours[:5]

array([  nan,  1.34,  7.  , 34.63, 12.76])

In [12]:
#11. Print the last 5 values of the hours array.
hours[:-5]

array([  nan,  1.34,  7.  , ..., 25.23,  7.21, 50.  ], shape=(49583,))

In [13]:
#12. Print every second value from the first 20 values.
hours[:20:2]

array([   nan,   7.  ,  12.76,    nan,   1.66,    nan,  11.63,  28.  ,
         0.59, 253.85])

In [14]:
#13. Reverse the array.
reversed_hours = hours[::-1]
print(reversed_hours)

[ nan 2.   5.   ... 7.   1.34  nan]


In [15]:
#14. Find the sum of the hours array.
print("Sum:",np.nansum(hours))
#np.sum(hours)

Sum: 2376713.1


In [16]:
#15. Find the mean, the minimum and the maximum of the hours array.
print("Mean:", np.nanmean(hours))
print("Minimum:", np.nanmin(hours))
print("Maximum:", np.nanmax(hours))

Mean: 63.614814913947704
Minimum: -12.5
Maximum: 9888.01


In [17]:
#16. Find the standard deviation.
print("Standard Deviation:",np.nanstd(hours))

Standard Deviation: 497.7190812291573


In [18]:
#17. Find the median.
print("Median:",np.nanmedian(hours))

Median: 13.13


In [19]:
#18. Count how many values are missing in the array.
print("Missing Values:",np.isnan(hours).sum())

Missing Values: 12227


In [20]:
#19. Find the mean while ignoring the missing values.
print("Mean:",np.nanmean(hours))

Mean: 63.614814913947704


In [21]:
#20. Replace all the missing values with 0.
hours_clean = np.nan_to_num(hours, nan=0)
print(hours_clean)

[0.   1.34 7.   ... 5.   2.   0.  ]


In [22]:
#21. Count how many values are greater than 100.
print(np.sum(hours > 100))

1633


In [23]:
#22. Show only the values that are greater than 100.
print(hours[hours > 100])

[ 253.85  128.   1900.66 ...  562.22  141.9   137.56]


In [24]:
#23. Show the values that are between 10 and 50.
print(hours[(hours >= 10) & (hours <= 50)])

[34.63 12.76 15.3  ... 25.23 50.   47.  ]


In [25]:
#24. Count how many values are negative.
print(np.sum(hours < 0))

140


In [26]:
#25. Replace all the negative values with 0.
hours[hours < 0] = 0
print(hours)

[ nan 1.34 7.   ... 5.   2.    nan]


In [27]:
#26. Sort the array from smallest to largest.
sorted_hours = np.sort(hours)
print(sorted_hours)

[ 0.  0.  0. ... nan nan nan]


In [35]:
#27. Find the position of the largest value.
print(np.nanargmax(hours))

10080


In [36]:
#28. Find the position of the smallest value.
print(np.nanargmin(hours))

75


In [39]:
#29. Find the 5 largest values.
print(np.sort(hours[~np.isnan(hours)])[-5:])

[8760.   8760.   8760.   9888.01 9888.01]


In [42]:
#30. Round every value to 1 decimal place.
rounded_hours = np.round(hours, 1)
print(rounded_hours)

[nan 1.3 7.  ... 5.  2.  nan]


In [43]:
#31. Multiply every value by 2.
hours_times_2 = hours * 2
print(hours_times_2)

[  nan  2.68 14.   ... 10.    4.     nan]


In [44]:
#32. Add 10 to every value.
hours_plus_10 = hours + 10
print(hours_plus_10)

[  nan 11.34 17.   ... 15.   12.     nan]


In [48]:
#33. Multiply the hours array by the billing rate array.
df["Billing Rate (USD)"] = (df["Billing Rate (USD)"].astype(str).str.replace("$", "", regex=False).str.replace(",", "", regex=False))
df["Billing Rate (USD)"] = pd.to_numeric(df["Billing Rate (USD)"],errors="coerce")
billing_rate = df["Billing Rate (USD)"].to_numpy().copy()
print(billing_rate.dtype)

billing_rate = df["Billing Rate (USD)"].to_numpy().copy()
total_amount = hours * billing_rate
print(total_amount)

float64
[    nan  44.421 336.7   ... 124.7   233.52      nan]


In [49]:
#34. Check whether the two arrays have the same length.
print(len(hours) == len(billing_rate))

True


In [50]:
#35. Use np.where to mark values above 24 as slow and the rest as fast.
speed = np.where(hours > 24, "slow", "fast")
print(speed)

['fast' 'fast' 'fast' ... 'fast' 'fast' 'fast']


In [52]:
df.columns

Index(['Record_ID', 'ticket id', 'ClientID', 'Client Name ', 'client_industry',
       'Client_Country', 'client city', 'Contract Type', 'ServiceLine',
       'project_code', 'Engagement Start Date', 'engagement_end_date ',
       'Ticket_Created_At', 'ticket resolved at', 'PRIORITY', 'Status',
       'category ', 'Assigned Engineer', 'engineer_Email', 'EngineerLevel',
       'engineer_experience_years', 'Billing Rate (USD)', 'hours_logged',
       'Billable Amount USD', 'SLA_Hours', 'resolution time hours',
       'SLA Breached', 'CSAT Score', 'Customer Comment'],
      dtype='str')

In [54]:
#36. Make an array of the unique priority values.
priority = df["PRIORITY"].dropna().to_numpy().copy()
unique_priority = np.unique(priority)
print(unique_priority)

[' ' '-' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High'
 'LOW' 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4'
 'PRIORITY' 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3' 'p4']


In [55]:
#37. Count how many times each unique priority value appears.
unique_priority, priority_counts = np.unique(priority,return_counts=True)
print(unique_priority)
print(priority_counts)

[' ' '-' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High'
 'LOW' 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4'
 'PRIORITY' 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3' 'p4']
[  97  108  111 1992 2019 1995 1968   90 2047 2063 2005 2059 2002 1900
 2013 2015 1945 2044 1967 2010 1930    4 2029 2003 2072  128  132 1993
 1961 2069 1961]


In [57]:
#38. Take the first 100 values and reshape them into a 10 by 10 array.
array_100 = hours[:100].reshape(10, 10)
array_100

array([[        nan, 1.34000e+00, 7.00000e+00, 3.46300e+01, 1.27600e+01,
        1.53000e+01,         nan, 9.00000e+00, 1.66000e+00,         nan],
       [        nan, 1.44000e+00, 1.16300e+01, 7.23100e+01, 2.80000e+01,
        1.01600e+01, 5.90000e-01, 7.00000e+00, 2.53850e+02, 4.20000e+00],
       [5.08100e+01, 8.01000e+00, 6.79400e+01,         nan, 3.27100e+01,
                nan, 6.91000e+00, 3.08400e+01, 3.51000e+00, 4.34000e+00],
       [1.80000e+01, 3.14400e+01, 3.42000e+00, 2.44600e+01,         nan,
        1.30000e+01, 3.00200e+01, 1.15100e+01, 6.30200e+01, 1.03000e+00],
       [        nan, 3.92000e+00, 2.02200e+01, 2.41500e+01, 8.40000e+01,
                nan, 2.70000e+01,         nan, 4.00000e+00, 2.76000e+00],
       [1.12600e+01, 2.40000e+01, 5.26000e+00, 1.40000e+01, 5.00000e+00,
        1.14100e+01,         nan, 1.80000e+01, 1.28000e+02, 1.54000e+01],
       [1.90066e+03, 4.00000e+00, 3.00000e+00, 9.00000e+00, 1.33350e+02,
                nan, 4.00000e+00,         nan

In [58]:
#39. Transpose that 10 by 10 array.
transposed_array = array_100.T
transposed_array

array([[        nan,         nan, 5.08100e+01, 1.80000e+01,         nan,
        1.12600e+01, 1.90066e+03, 2.05100e+01, 1.91700e+01, 1.30000e+01],
       [1.34000e+00, 1.44000e+00, 8.01000e+00, 3.14400e+01, 3.92000e+00,
        2.40000e+01, 4.00000e+00, 1.13300e+01, 1.78600e+01, 1.09100e+01],
       [7.00000e+00, 1.16300e+01, 6.79400e+01, 3.42000e+00, 2.02200e+01,
        5.26000e+00, 3.00000e+00, 5.99100e+01, 9.21000e+00, 8.00000e+00],
       [3.46300e+01, 7.23100e+01,         nan, 2.44600e+01, 2.41500e+01,
        1.40000e+01, 9.00000e+00, 1.00000e+00, 5.40000e+01, 3.81000e+00],
       [1.27600e+01, 2.80000e+01, 3.27100e+01,         nan, 8.40000e+01,
        5.00000e+00, 1.33350e+02, 2.29700e+01,         nan, 3.73680e+02],
       [1.53000e+01, 1.01600e+01,         nan, 1.30000e+01,         nan,
        1.14100e+01,         nan, 0.00000e+00, 2.00000e+01, 1.13800e+01],
       [        nan, 5.90000e-01, 6.91000e+00, 3.00200e+01, 2.70000e+01,
                nan, 4.00000e+00,         nan

In [60]:
#40. Flatten it back into a 1-D array.
flattened_array = transposed_array.flatten()
flattened_array

array([        nan,         nan, 5.08100e+01, 1.80000e+01,         nan,
       1.12600e+01, 1.90066e+03, 2.05100e+01, 1.91700e+01, 1.30000e+01,
       1.34000e+00, 1.44000e+00, 8.01000e+00, 3.14400e+01, 3.92000e+00,
       2.40000e+01, 4.00000e+00, 1.13300e+01, 1.78600e+01, 1.09100e+01,
       7.00000e+00, 1.16300e+01, 6.79400e+01, 3.42000e+00, 2.02200e+01,
       5.26000e+00, 3.00000e+00, 5.99100e+01, 9.21000e+00, 8.00000e+00,
       3.46300e+01, 7.23100e+01,         nan, 2.44600e+01, 2.41500e+01,
       1.40000e+01, 9.00000e+00, 1.00000e+00, 5.40000e+01, 3.81000e+00,
       1.27600e+01, 2.80000e+01, 3.27100e+01,         nan, 8.40000e+01,
       5.00000e+00, 1.33350e+02, 2.29700e+01,         nan, 3.73680e+02,
       1.53000e+01, 1.01600e+01,         nan, 1.30000e+01,         nan,
       1.14100e+01,         nan, 0.00000e+00, 2.00000e+01, 1.13800e+01,
               nan, 5.90000e-01, 6.91000e+00, 3.00200e+01, 2.70000e+01,
               nan, 4.00000e+00,         nan, 6.00000e+00, 3.367

In [61]:
#41. Join two arrays together using np.concatenate.
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
joined_array = np.concatenate((array1, array2))
print(joined_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [62]:
#42. Split an array into 5 equal parts.
parts = np.array_split(hours, 5)

for part in parts:
    print(part)

[  nan  1.34  7.   ... 22.92 17.44  4.47]
[  nan   nan 32.   ...  1.     nan  7.66]
[ 6.65  1.   27.47 ... 58.    1.86   nan]
[11.76   nan   nan ... 57.1  19.04   nan]
[47.52  5.    5.3  ...  5.    2.     nan]


In [63]:
#43. Find the 25th, 50th and 75th percentile.
percentiles = np.nanpercentile(hours,[25, 50, 75])
print(percentiles)

[ 4.34 13.13 29.45]


In [65]:
#44. Find the cumulative sum of the first 20 values.
cumulative_sum = np.nancumsum(hours[:20])
print(cumulative_sum)

[  0.     1.34   8.34  42.97  55.73  71.03  71.03  80.03  81.69  81.69
  81.69  83.13  94.76 167.07 195.07 205.23 205.82 212.82 466.67 470.87]


In [66]:
#45. Find the difference between each value and the one before it using np.diff.
differences = np.diff(hours)
print(differences)

[   nan   5.66  27.63 ... -42.    -3.      nan]


In [67]:
#46. Keep every value inside the range 0 to 100 using np.clip.
clipped_hours = np.clip(hours, 0, 100)
print(clipped_hours)

[ nan 1.34 7.   ... 5.   2.    nan]


In [69]:
#47. Convert the array to whole numbers.
whole_hours = np.nan_to_num(hours, nan=0).astype(int)
print(whole_hours)

[0 1 7 ... 5 2 0]


In [71]:
#48. Copy the array, change one value in the copy, and show that the original did not change.
hours_copy = hours.copy()
hours_copy[2] = 999
print("Original:", hours[2])
print("Copy:", hours_copy[2])

Original: 7.0
Copy: 999.0


In [72]:
#49. Save the array to a .npy file and load it back.
np.save("hours_array.npy", hours)
loaded_hours = np.load("hours_array.npy")
print(loaded_hours)

[ nan 1.34 7.   ... 5.   2.    nan]


In [73]:
#50. Find the total revenue using np.dot on the hours array and the rate array.
valid = ~np.isnan(hours) & ~np.isnan(billing_rate)
total_revenue = np.dot(hours[valid], billing_rate[valid])
print(total_revenue)

146746158.27169985
